// Package corpus is the named set of scenes every parity gate runs against.
//
// An Entry pairs a scene with the tolerance it has EARNED (see internal/parity):
// Identical where both backends run the same integer/analytic path, Quantized
// where independent float pipelines round to 8 bits, and a named Budget only
// where a specific operation is known to diverge. Feature phases add entries
// here rather than hand-writing another one-off parity test.
//
// Tol is the CROSS-BACKEND gate — CPU versus GPU. It is not the golden gate: a
// golden is generated by the deterministic CPU reference, so a backend compared
// against its own stored output is gated at Identical regardless of Tol.
package corpus

import (
	"github.com/stohirov/suren/internal/parity"
	"github.com/stohirov/suren/internal/sample"
	"github.com/stohirov/suren/paint"
	"github.com/stohirov/suren/scene"
)

type Entry struct {
	Name  string
	W, H  int
	Build func() *scene.Scene
	Tol   parity.Config
}

var blendModes = []struct {
	name string
	op   paint.BlendMode
	tol  parity.Config
}{
	// "normal", not "srcover": Phase 15 gave that name to the Porter-Duff
	// operator it always belonged to. This row is the blend axis's identity.
	{"normal", paint.Normal, parity.Quantized()},
	{"multiply", paint.Multiply, parity.Quantized()},
	{"screen", paint.Screen, parity.Quantized()},
	{"overlay", paint.Overlay, parity.Quantized()},
	{"darken", paint.Darken, parity.Quantized()},
	{"lighten", paint.Lighten, parity.Quantized()},
	// These two carried Budget(2) and Budget(3) from Phase 10 until Phase 13
	// pinned the shader's rounding. The budgets named the division as the culprit,
	// which was wrong: the division only AMPLIFIED a backdrop that the two
	// backends had quantized differently. With the GPU rounding per node the way
	// the CPU reference does, both now hold the ordinary floor — retired by a fix
	// rather than widened.
	{"color-dodge", paint.ColorDodge, parity.Quantized()},
	{"color-burn", paint.ColorBurn, parity.Quantized()},
	{"hard-light", paint.HardLight, parity.Quantized()},
	{"soft-light", paint.SoftLight, parity.Quantized()},
	{"difference", paint.Difference, parity.Quantized()},
	{"exclusion", paint.Exclusion, parity.Quantized()},
}

// compositeOps is the full Porter-Duff set. It is exhaustive on purpose: the
// operators differ only in two coefficients, so a table with a wrong row looks
// exactly like a table with a right one until the row is rendered.
var compositeOps = []struct {
	name string
	op   paint.CompositeOp
}{
	{"src-over", paint.SrcOver},
	{"clear", paint.Clear},
	{"src", paint.Src},
	{"dst", paint.Dst},
	{"dst-over", paint.DstOver},
	{"src-in", paint.SrcIn},
	{"dst-in", paint.DstIn},
	{"src-out", paint.SrcOut},
	{"dst-out", paint.DstOut},
	{"src-atop", paint.SrcAtop},
	{"dst-atop", paint.DstAtop},
	{"xor", paint.Xor},
}

func All() []Entry {
	entries := []Entry{
		{"solid", sample.W, sample.H, sample.Scene, parity.Quantized()},
		{"gradient", sample.W, sample.H, sample.GradientScene, parity.Quantized()},
		// The pair is the measurement, as with fallback-gradient. Closed is the
		// conic gradient the floor covers on its merits — continuous paint, so the
		// f32-vs-f64 atan2 difference stays sub-LSB. Seam contains a colour
		// discontinuity along the ray at Angle, which no tolerance can own in
		// general (see paint.ConicGradient); it holds at the floor because no pixel
		// centre in THIS scene lands within f32's reach of that ray, and it is here
		// to gate where the seam falls, not to suggest a seam is safe.
		{"gradient-conic", sample.W, sample.H, func() *scene.Scene { return sample.ConicScene(false) }, parity.Quantized()},
		{"gradient-conic-seam", sample.W, sample.H, func() *scene.Scene { return sample.ConicScene(true) }, parity.Quantized()},
		// Quantized, and the plan expected otherwise: Phase 16 predicted mesh
		// interpolation would miss the exact floor and need perceptual mode. That
		// prediction was about COONS patches, whose device→parameter inverse is a
		// per-pixel Newton solve; a Gouraud triangle's inverse is a closed-form
		// linear solve, so it sits at the floor like every other paint and needs
		// neither perceptual mode nor Phase 14's fallback. Measured Δ=1.
		//
		// This entry also gates paint.MeshEps: its geometry puts pixel centres
		// exactly on shared diagonals, which is how the hairline crack was found
		// (Δ=198). Note what a golden alone would have done here — recorded the
		// crack as expected output and gated it forever. Only the differential saw
		// it, because the bug was in the REFERENCE.
		{"mesh", sample.W, sample.H, sample.MeshScene, parity.Quantized()},
		{"many-nodes", 640, 360, func() *scene.Scene { return sample.ManyNodes(640, 360, 40, 24) }, parity.Identical()},
		{"many-segments", 400, 300, func() *scene.Scene { return sample.ManySegments(400, 300, 300) }, parity.Quantized()},
		{"clip-rect", 96, 96, sample.ClipRectScene, parity.Identical()},
		{"clip-path", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(false) }, parity.Quantized()},
		{"clip-path-nested", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(true) }, parity.Quantized()},
		// Δ=0, not the floor: pixel-aligned solid quads leave no coverage or
		// gradient to round differently, so the only thing these can measure is
		// whether both backends quantize each node the same way. They gate
		// Phase 13's per-node rounding, and 64 deep is where a regression shows as
		// Δ=10 rather than as the single LSB visible at typical depths.
		{"blend-stack-normal", 96, 96, func() *scene.Scene { return sample.BlendStack(64, paint.Normal) }, parity.Identical()},
		{"blend-stack-overlay", 96, 96, func() *scene.Scene { return sample.BlendStack(64, paint.Overlay) }, parity.Identical()},
		// Identical because of the fallback, not despite it: this scene holds a
		// gradient that the GPU renders at Δ=1, marked for per-tile CPU fallback
		// (Phase 14). Δ=0 over the whole frame is only reachable if the CPU patch
		// is bit-exact and lands on exactly the flagged tiles. The same scene
		// without the mark is the entry below, and it sits at the floor — the pair
		// is what makes this gate non-vacuous.
		{"fallback-gradient", sample.FallbackW, sample.FallbackH, func() *scene.Scene { return sample.FallbackScene(true) }, parity.Identical()},
		{"fallback-gradient-off", sample.FallbackW, sample.FallbackH, func() *scene.Scene { return sample.FallbackScene(false) }, parity.Quantized()},
	}
	for _, b := range blendModes {
		entries = append(entries, Entry{
			Name:  "blend-" + b.name,
			W:     sample.W,
			H:     sample.H,
			Build: func() *scene.Scene { return sample.BlendScene(b.op) },
			Tol:   b.tol,
		})
	}
	// One entry per Porter-Duff operator (Phase 15), each over all three backdrop
	// regimes — see sample.CompositeScene. No operator earned a budget; if one
	// ever does, the reason goes here and not into a widened default.
	//
	// These measure Δ=0 on Metal today, but they are gated at Quantized and not
	// Identical, and the gap is deliberate. Identical is the contract's gate for
	// paths where the two backends run the same integer/analytic arithmetic and
	// so CANNOT diverge. These do not qualify: porterDuff unpremultiplies through
	// a division and lerps by coverage, all in f32 against the reference's f64.
	// Δ=0 here is a fact about these colors on this driver, not a property, and
	// gating on it would be reading luck as a guarantee.
	for _, o := range compositeOps {
		entries = append(entries, Entry{
			Name:  "composite-" + o.name,
			W:     sample.W,
			H:     sample.H,
			Build: func() *scene.Scene { return sample.CompositeScene(o.op, paint.Normal) },
			Tol:   parity.Quantized(),
		})
	}
	// The two axes crossed. Every entry above leaves the blend axis at Normal and
	// every blend-* entry leaves the composite axis at SrcOver, so neither family
	// can see the two being confused for one another — and the GPU packs both
	// into one flags word, so confusing them is an off-by-one away.
	//
	// This is measured, not hypothesized. Widening the shader's blend-mode mask
	// from 0xF to 0xFF lets the composite bits leak into the mode, and every
	// single-axis entry above still PASSES: with one axis at its zero value the
	// leaked bits either are zero or land past the end of blendCh's switch, where
	// the default returns the source color — which is exactly what Normal does.
	// The four entries below are the complete set that goes red.
	for _, x := range []struct {
		name string
		op   paint.CompositeOp
		mode paint.BlendMode
	}{
		{"xor-multiply", paint.Xor, paint.Multiply},
		{"src-atop-overlay", paint.SrcAtop, paint.Overlay},
		{"dst-over-difference", paint.DstOver, paint.Difference},
		{"src-in-color-dodge", paint.SrcIn, paint.ColorDodge},
	} {
		entries = append(entries, Entry{
			Name:  "composite-x-blend-" + x.name,
			W:     sample.W,
			H:     sample.H,
			Build: func() *scene.Scene { return sample.CompositeScene(x.op, x.mode) },
			Tol:   parity.Quantized(),
		})
	}
	// Regressions are embedded at compile time, so a decode failure is a defect
	// in the tree rather than a runtime condition a caller could handle. It
	// panics rather than dropping the entry, because a fuzz find that silently
	// stops being checked is the exact failure this directory exists to prevent.
	regs, err := Regressions()
	if err != nil {
		panic("corpus: loading fuzz regressions: " + err.Error())
	}
	return append(entries, regs...)
}
