// Package corpus is the named set of scenes every parity gate runs against.
//
// An Entry pairs a scene with the tolerance it has EARNED (see internal/parity):
// Identical where both backends run the same integer/analytic path, Quantized
// where independent float pipelines round to 8 bits, and a named Budget only
// where a specific operation is known to diverge. Feature phases add entries
// here rather than hand-writing another one-off parity test.
//
// Tol is the CROSS-BACKEND gate — CPU versus GPU. It is not the golden gate: a
// golden is generated by the deterministic CPU reference, so a backend compared
// against its own stored output is gated at Identical regardless of Tol.
package corpus

import (
	"github.com/stohirov/sukho/internal/parity"
	"github.com/stohirov/sukho/internal/sample"
	"github.com/stohirov/sukho/paint"
	"github.com/stohirov/sukho/scene"
)

type Entry struct {
	Name  string
	W, H  int
	Build func() *scene.Scene
	Tol   parity.Config
}

var blendModes = []struct {
	name string
	op   paint.BlendMode
	tol  parity.Config
}{
	{"srcover", paint.SrcOver, parity.Quantized()},
	{"multiply", paint.Multiply, parity.Quantized()},
	{"screen", paint.Screen, parity.Quantized()},
	{"overlay", paint.Overlay, parity.Quantized()},
	{"darken", paint.Darken, parity.Quantized()},
	{"lighten", paint.Lighten, parity.Quantized()},
	// These two carried Budget(2) and Budget(3) from Phase 10 until Phase 13
	// pinned the shader's rounding. The budgets named the division as the culprit,
	// which was wrong: the division only AMPLIFIED a backdrop that the two
	// backends had quantized differently. With the GPU rounding per node the way
	// the CPU reference does, both now hold the ordinary floor — retired by a fix
	// rather than widened.
	{"color-dodge", paint.ColorDodge, parity.Quantized()},
	{"color-burn", paint.ColorBurn, parity.Quantized()},
	{"hard-light", paint.HardLight, parity.Quantized()},
	{"soft-light", paint.SoftLight, parity.Quantized()},
	{"difference", paint.Difference, parity.Quantized()},
	{"exclusion", paint.Exclusion, parity.Quantized()},
}

func All() []Entry {
	entries := []Entry{
		{"solid", sample.W, sample.H, sample.Scene, parity.Quantized()},
		{"gradient", sample.W, sample.H, sample.GradientScene, parity.Quantized()},
		{"many-nodes", 640, 360, func() *scene.Scene { return sample.ManyNodes(640, 360, 40, 24) }, parity.Identical()},
		{"many-segments", 400, 300, func() *scene.Scene { return sample.ManySegments(400, 300, 300) }, parity.Quantized()},
		{"clip-rect", 96, 96, sample.ClipRectScene, parity.Identical()},
		{"clip-path", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(false) }, parity.Quantized()},
		{"clip-path-nested", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(true) }, parity.Quantized()},
		// Δ=0, not the floor: pixel-aligned solid quads leave no coverage or
		// gradient to round differently, so the only thing these can measure is
		// whether both backends quantize each node the same way. They gate
		// Phase 13's per-node rounding, and 64 deep is where a regression shows as
		// Δ=10 rather than as the single LSB visible at typical depths.
		{"blend-stack-srcover", 96, 96, func() *scene.Scene { return sample.BlendStack(64, paint.SrcOver) }, parity.Identical()},
		{"blend-stack-overlay", 96, 96, func() *scene.Scene { return sample.BlendStack(64, paint.Overlay) }, parity.Identical()},
		// Identical because of the fallback, not despite it: this scene holds a
		// gradient that the GPU renders at Δ=1, marked for per-tile CPU fallback
		// (Phase 14). Δ=0 over the whole frame is only reachable if the CPU patch
		// is bit-exact and lands on exactly the flagged tiles. The same scene
		// without the mark is the entry below, and it sits at the floor — the pair
		// is what makes this gate non-vacuous.
		{"fallback-gradient", sample.FallbackW, sample.FallbackH, func() *scene.Scene { return sample.FallbackScene(true) }, parity.Identical()},
		{"fallback-gradient-off", sample.FallbackW, sample.FallbackH, func() *scene.Scene { return sample.FallbackScene(false) }, parity.Quantized()},
	}
	for _, b := range blendModes {
		entries = append(entries, Entry{
			Name:  "blend-" + b.name,
			W:     sample.W,
			H:     sample.H,
			Build: func() *scene.Scene { return sample.BlendScene(b.op) },
			Tol:   b.tol,
		})
	}
	// Regressions are embedded at compile time, so a decode failure is a defect
	// in the tree rather than a runtime condition a caller could handle. It
	// panics rather than dropping the entry, because a fuzz find that silently
	// stops being checked is the exact failure this directory exists to prevent.
	regs, err := Regressions()
	if err != nil {
		panic("corpus: loading fuzz regressions: " + err.Error())
	}
	return append(entries, regs...)
}
