// Package corpus is the named set of scenes every parity gate runs against.
//
// An Entry pairs a scene with the tolerance it has EARNED (see internal/parity):
// Identical where both backends run the same integer/analytic path, Quantized
// where independent float pipelines round to 8 bits, and a named Budget only
// where a specific operation is known to diverge. Feature phases add entries
// here rather than hand-writing another one-off parity test.
//
// Tol is the CROSS-BACKEND gate — CPU versus GPU. It is not the golden gate: a
// golden is generated by the deterministic CPU reference, so a backend compared
// against its own stored output is gated at Identical regardless of Tol.
package corpus

import (
	"github.com/stohirov/sukho/internal/parity"
	"github.com/stohirov/sukho/internal/sample"
	"github.com/stohirov/sukho/paint"
	"github.com/stohirov/sukho/scene"
)

type Entry struct {
	Name  string
	W, H  int
	Build func() *scene.Scene
	Tol   parity.Config
}

var blendModes = []struct {
	name string
	op   paint.BlendMode
	tol  parity.Config
}{
	{"srcover", paint.SrcOver, parity.Quantized()},
	{"multiply", paint.Multiply, parity.Quantized()},
	{"screen", paint.Screen, parity.Quantized()},
	{"overlay", paint.Overlay, parity.Quantized()},
	{"darken", paint.Darken, parity.Quantized()},
	{"lighten", paint.Lighten, parity.Quantized()},
	{"color-dodge", paint.ColorDodge, parity.Budget(2, "cb/(1-cs) division diverges at the min(1,·) clamp in f32 vs f64")},
	{"color-burn", paint.ColorBurn, parity.Budget(3, "(1-cb)/cs division diverges at the min(1,·) clamp in f32 vs f64")},
	{"hard-light", paint.HardLight, parity.Quantized()},
	{"soft-light", paint.SoftLight, parity.Quantized()},
	{"difference", paint.Difference, parity.Quantized()},
	{"exclusion", paint.Exclusion, parity.Quantized()},
}

func All() []Entry {
	entries := []Entry{
		{"solid", sample.W, sample.H, sample.Scene, parity.Quantized()},
		{"gradient", sample.W, sample.H, sample.GradientScene, parity.Quantized()},
		{"many-nodes", 640, 360, func() *scene.Scene { return sample.ManyNodes(640, 360, 40, 24) }, parity.Identical()},
		{"many-segments", 400, 300, func() *scene.Scene { return sample.ManySegments(400, 300, 300) }, parity.Quantized()},
		{"clip-rect", 96, 96, sample.ClipRectScene, parity.Identical()},
		{"clip-path", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(false) }, parity.Quantized()},
		{"clip-path-nested", sample.W, sample.H, func() *scene.Scene { return sample.ClipPathScene(true) }, parity.Quantized()},
	}
	for _, b := range blendModes {
		entries = append(entries, Entry{
			Name:  "blend-" + b.name,
			W:     sample.W,
			H:     sample.H,
			Build: func() *scene.Scene { return sample.BlendScene(b.op) },
			Tol:   b.tol,
		})
	}
	return entries
}
