package cpu

import (
	"testing"

	"github.com/stohirov/suren/internal/corpus"
	"github.com/stohirov/suren/internal/goldentest"
	"github.com/stohirov/suren/internal/parity"
)

// The golden gate is Identical, not the entry's Tol: goldens are generated by
// this deterministic reference, so re-rendering must reproduce them bit-for-bit.
// The entry's Tol is the cross-backend gate and belongs to the GPU parity test.
// This also runs without a GPU, so it catches CPU drift in plain CI.
func TestGoldenCorpus(t *testing.T) {
	for _, e := range corpus.All() {
		t.Run(e.Name, func(t *testing.T) {
			goldentest.AssertExact(t, e.Name+".png", Render(e.Build(), e.W, e.H), parity.Identical())
		})
	}
}
